### ISSUE TITLE
说好的扫描屏幕二维码呢 怎么是截屏😒🙄

### ISSUE THREAD

**Issue by yFFyF** [ekibun/TilesBox#3]
RT
点save还有几率停止运行或者就是什么反应都没有
![Screenshot_20190321-225057](https://user-images.githubusercontent.com/6211117/54760823-d60d2080-4c2b-11e9-9e0c-85810493f3a9.png)

**Comment by yFFyF** [comment]
换了个ROM 界面变了 也可以用了，调用的系统的吗？大概可能是我这边的问题🤥

**Comment by zhuxf8** [comment]
一加5氢OS8.1提示缺少权限，在提示对话框里点确定点了没反应。
